absolute_urls: false

home:
  alias: '/home'
  hide_in_urls: true

pages:
  theme: baseline
  markdown:
    extra: false
  process:
    markdown: true
    twig: false

cache:
  enabled: false
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: false
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: false
  css_rewrite: false
  js_pipeline: false
  js_minify: false

errors:
  display: true
  log: false

debugger:
  enabled: true
  twig: false
  shutdown:
    close_connection: true
gpm:
  releases: stable
  verify_peer: true
